### ISSUE TITLE
nargo check error with ecrecover

### ISSUE THREAD

**Issue by s4rv4d** [colinnielsen/ecrecover-noir#19]
Getting an error while importing ecrecover dependency

```
error: Integers must have the same bit width LHS is 64, RHS is 8
  ┌─ ../noir-array-helpers/v0.30.0/src/lib.nr:7:22
  │
7 │             value |= (arr_a[i * 8 + j] as u64) << ((56 - j * 8) as u8);
  │                      -------------------------------------------------
  │

error: Integers must have the same bit width LHS is 64, RHS is 8
   ┌─ ../noir-array-helpers/v0.30.0/src/lib.nr:14:22
   │
14 │             value |= (arr_b[(i - 4) * 8 + j] as u64) << ((56 - j * 8) as u8);
   │                      -------------------------------------------------------
   │
```

**Comment by SIDHARTH20K4** [comment]
dealing with the same issue

**Comment by SIDHARTH20K4** [comment]
@s4rv4d 
try running this 

use dep::std;

fn main(
    hashed_message : [u8;32],
    pub_key_x : [u8;32],
    pub_key_y : [u8;32],
    signature : [u8;64],
    ) {
    let valid_signature = std::ecdsa_secp256k1::verify_signature(pub_key_x, pub_key_y, signature, hashed_message);
    assert(valid_signature);
}

**Comment by Niferu** [comment]
It is a poor solution, but you can also downgrade noir to version `1.0.0-beta.3` then remember to run `bbup` to update backend to compatible version as well if you are using it ofc.

**Comment by Ubaid-ch** [comment]
Dealing with same issue

**Comment by SIDHARTH20K4** [comment]
> It is a poor solution, but you can also downgrade noir to version `1.0.0-beta.3` then remember to run `bbup` to update backend to compatible version as well if you are using it ofc.

yes.. forgot to mention the downgrade alternative!

**Comment by acharb** [comment]
for anyone that comes here - the fix has been merged into https://github.com/colinnielsen/noir-array-helpers/releases/tag/v0.30.1 , but this repo hasn't been updated to use it yet

manually going into your nargo cache file and updating the version fixes it until [the update ](https://github.com/colinnielsen/ecrecover-noir/pull/21)is merged

```
// in ~/nargo/github.com/colinnielsen/ecrecover-noir update the version to v0.30.1 or higher:

array_helpers = { tag = "v0.30.2", git = "https://github.com/colinnielsen/noir-array-helpers" }
```

**Comment by Princeigwe** [comment]
[dependencies]
array_helpers = { tag = "v0.30.2", git = "https://github.com/colinnielsen/noir-array-helpers" }
ecrecover = { tag = "v1.0.0", git = "https://github.com/colinnielsen/ecrecover-noir" }

This is what I have in my Nargo.toml file, and I still have the error. I'm not sure of what I'm doing wrong.

**Comment by jhuhnke** [comment]
@Princeigwe - you need to update the version of the array_helpers dependency within your local installation of nargo. Ecrecover is preinstalled there, and the version of array_helpers is set to 0.30.0 as a default within the nargo.toml. 

Once you change the version there and save, you can remove ecrecover from your local project's nargo.toml and then be good to go.

**Comment by colinnielsen** [comment]
my GUYS - I'm sorry this took a while @jhuhnke @Princeigwe @acharb @SIDHARTH20K4 @Ubaid-ch @Niferu @s4rv4d this should be G2G now

**Comment by wilmer-daza** [comment]
I'm still having the problem, even though I'm using v1.0.2 that uses the v0.30.4 of array helpers
